services:
  proposal-builder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8501"
    restart: always
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
